DROP TABLE IF EXISTS ACCOUNT;  
CREATE TABLE ACCOUNT (  
ID INT AUTO_INCREMENT  PRIMARY KEY,  
Account_Number INT(12) NOT NULL,  
Pin INT(4) NOT NULL,
Opening_Balance INT(10) NOT NULL,
Over_draft INT(8) NOT NULL,
Balance INT(8) NOT NULL
); 